name: Deploy to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "=== Starting Auto-Deployment ==="
          echo "Timestamp: $(date)"
          
          # Navigate to project directory
          cd ~/Attendance-Management-System
          
          # Pull latest changes
          echo "Pulling latest changes from GitHub..."
          git pull origin main
          
          # Stop current containers
          echo "Stopping current containers..."
          docker-compose down
          
          # Rebuild and start containers
          echo "Rebuilding and starting containers..."
          docker-compose up -d --build
          
          # Wait a moment for containers to start
          sleep 10
          
          # Check if containers are running
          echo "Checking container status..."
          docker-compose ps
          
          # Test if application is responding
          echo "Testing application..."
          if curl -s -o /dev/null -w "%{http_code}" https://attendance-app.com | grep -q "200\|301\|302"; then
            echo "✅ Deployment completed successfully!"
            echo "Application is accessible at: https://attendance-app.com"
          else
            echo "⚠️  Deployment may have issues. Check logs:"
            echo "docker-compose logs"
          fi
          
          echo "=== Auto-Deployment Completed ==="
          echo "Timestamp: $(date)" 